export const LOGIN = "/login";
export const LIGA_INSCRIPCION = "/liga-pre-inscripcion";
export const REGISTER = "/register";
export const JUGADORES = "/jugadores"
export const RESULTADOS = "/resultados"
export const CONFIRMACION_RESULTADO = "/confirmar-resultado"
export const TABLA_POSICIONES = "/posiciones"
export const PRE_INSCRIPCIONES = "/pre-inscripciones"
export const CONFIRMAR_INSCRIPCION = "/confirmar-inscripcion"
export const CHECK_INSCRIPCION = "/check-inscripcion"
export const BORRAR_JUGADOR = "/borrar-jugador";
export const ASIGNAR_EQUIPO = "/asignar-equipo";
export const CATEGORIAS = "/categorias";
// export const JUGADORES_LIGA = "/jugadores-liga"